### ISSUE TITLE
drawing wire has bug due to hovering, and some pins are not working properly

### ISSUE THREAD

**Issue by EV-OD** [EV-OD/Digital-Logic#7]

**Comment by pk-021** [comment]
The drawing functions for the pins assigned the center of the output pins incorrectly because the width of the chip was not being accounted. The width was being added in the onMouseHovering function for the pins which is poor design. It caused the hover to work correctly but the center of the pin was being updated incorrectly which caused the bug. Now, in #8 , I have updated the centers correctly in the drawing function for the chip. and the pins only require the drawing functions to be called since the position is already set by the chip.

**Comment by EV-OD** [comment]
thank you for your contribution, I have merged the pull request
